con:
  token: '' # Discord bot token

mysql: # MySQL database credentials
  host: ''
  user: ''
  password: ''
  database: ''

music:
  lastfm: '' # last.fm api key
  lavalink:
    host: '' # lavalink node host ip
    port: 2333
    password: ''
    identifier: '' # lavalink node name
    retryAmount: 3
    retryDelay: 5000
    secure: false